name: Update tokens from Figma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          yarn

      - name: Build design tokens
        run: |
          yarn build:tokens

      - name: Build storybook
        run: |
          yarn build:storybook

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit staged files
        run: git commit -m "Updating assets from new tokens"

      - name: Fetch from main
        run: git fetch origin main

      - name: Push code to main
        run: git push origin HEAD:master
